# Generated by Django 4.2 on 2023-04-06 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Phone_Number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be in the format +123-456789012', regex='^0\\d{9}$')]),
        ),
    ]
